### PR TITLE
Beef up the readme

### PR DESCRIPTION
**Pull request by imduffy15**
The readme is fairly outdated, it fail to mention the AKS and EKS drivers.

This commit updates it to include them, discuss how to authenticate and give an example run.

Signed-off-by: Ian Duffy <ian@ianduffy.ie>

### CODE REVIEW

**Comment by nathan-jenan-rancher** [comment]
LGTM

**Comment by imduffy15** [comment]
@nathan-jenan-rancher Any chance of getting the released page updated with a latest build? Might be confusing for users who discover the project as the aks and eks drivers aren’t in the released version and the binary even when ran in debug mode doesn’t give a clear indication of no such driver.

**Comment by daxmc99** [comment]
Hi @imduffy15,
Is this still relevant? I would be willing to take a quick look at this if you would like

**Comment by imduffy15** [comment]
Still relevant... its just documentation updates.

**Comment by imduffy15** [comment]
Closing due to no follow up, merge or requested changes. Sad to see you guys not being more active on PRs. //cc @ibuildthecloud

**Pull request closed without merging**
